module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/tests/**/*.test.ts'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { isolatedModules: true }],
  },
  moduleNameMapper: {
    '^react$': '<rootDir>/node_modules/react',
    '^react/(.*)$': '<rootDir>/node_modules/react/$1',
    '^react-dom$': '<rootDir>/node_modules/react-dom',
    '^react-dom/(.*)$': '<rootDir>/node_modules/react-dom/$1',
    '^@churchos/frontend-contracts$': '<rootDir>/packages/frontend-contracts/src/index.ts',
    '^@churchos/tenant-core$': '<rootDir>/packages/tenant-core/src/index.ts',
    '^@churchos/types$': '<rootDir>/packages/types/src/index.ts',
    '^@churchos/config$': '<rootDir>/packages/config/src/index.ts',
    '^@churchos/ui$': '<rootDir>/packages/ui/src/index.ts',
  },
  verbose: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  modulePathIgnorePatterns: ['<rootDir>/dist'],
};
