export type SurfacePhaseKey = 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI' | 'VII' | 'VIII' | 'IX';
export type SurfaceKind =
  | 'gateway'
  | 'access'
  | 'permission'
  | 'standalone'
  | 'archive'
  | 'detail'
  | 'form'
  | 'portal'
  | 'immersive'
  | 'global'
  | 'state'
  | 'modal';
export type SurfacePlacement = 'header' | 'rail' | 'global' | 'none';
export type SurfaceRenderMode = 'static' | 'blueprint' | 'embedded';

export interface BlueprintField {
  name: string;
  label: string;
  type: 'text' | 'email' | 'tel' | 'number' | 'textarea' | 'select' | 'date' | 'time' | 'checkbox' | 'file';
  required?: boolean;
  options?: string[];
  helper?: string;
}

export interface BlueprintSurface {
  key: string;
  phase: SurfacePhaseKey;
  phaseTitle: string;
  phaseTotal: number;
  phaseItem: string;
  checklistLabel: string;
  title: string;
  slug: string;
  aliases?: string[];
  kind: SurfaceKind;
  placement: SurfacePlacement;
  renderMode: SurfaceRenderMode;
  endpoint: string;
  moduleKey: string;
  summary: string;
  primaryAction: string;
  secondaryAction?: string;
  fields?: BlueprintField[];
  signals?: string[];
  existingTemplate?: string;
}

const PHASE_TITLES: Record<SurfacePhaseKey, string> = {
  I: 'Gateway & Security Surfaces',
  II: 'Core Public-Facing Standalone Pages & Directories',
  III: 'Deep-Tier Templated Post Layouts',
  IV: 'High-Converting Custom Form Pages',
  V: 'Private Member & Discipleship Portals',
  VI: 'Immersive Virtual Spaces',
  VII: 'Global Embedded UI Components',
  VIII: 'Transactional Success & State Screens',
  IX: 'Error, Validation, & Permission Intercept Modals',
};

const PHASE_TOTALS: Record<SurfacePhaseKey, number> = {
  I: 10,
  II: 13,
  III: 7,
  IV: 24,
  V: 5,
  VI: 4,
  VII: 4,
  VIII: 6,
  IX: 15,
};

const defaultSignals = [
  'Tenant scoped request headers',
  'Custom validation states',
  'Draft restore on network loss',
];

function surface(input: Omit<BlueprintSurface, 'phaseTitle' | 'phaseTotal' | 'signals'> & { signals?: string[] }): BlueprintSurface {
  return {
    ...input,
    phaseTitle: PHASE_TITLES[input.phase],
    phaseTotal: PHASE_TOTALS[input.phase],
    signals: input.signals || defaultSignals,
  };
}

const basicIdentityFields: BlueprintField[] = [
  { name: 'firstName', label: 'First name', type: 'text', required: true },
  { name: 'lastName', label: 'Last name', type: 'text', required: true },
  { name: 'email', label: 'Email address', type: 'email', required: true },
  { name: 'phone', label: 'Phone number', type: 'tel' },
];

const registrationFields: BlueprintField[] = [
  ...basicIdentityFields,
  { name: 'campus', label: 'Preferred campus', type: 'select', required: true, options: ['Central Campus', 'North Campus', 'Online Campus'] },
  { name: 'notes', label: 'Notes for the care team', type: 'textarea' },
];

const consentField: BlueprintField = {
  name: 'consent',
  label: 'I consent to secure follow-up from the church team',
  type: 'checkbox',
  required: true,
};

export const SURFACE_CATALOG: BlueprintSurface[] = [
  surface({
    key: 'select-campus-gateway',
    phase: 'I',
    phaseItem: '1.1.',
    checklistLabel: 'Select Your Campus Gateway',
    title: 'Select Your Campus',
    slug: 'select-campus',
    kind: 'gateway',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/frontend-surfaces/select-campus/submit',
    moduleKey: 'domain-tenant-management',
    summary: 'Choose a localized branch before the Ecclesia shell loads tenant schedules and theme presets.',
    primaryAction: 'Set Campus',
    fields: [
      { name: 'campus', label: 'Campus or branch', type: 'select', required: true, options: ['Central Campus', 'North Campus', 'Online Campus', 'Global Missions Hub'] },
      { name: 'language', label: 'Preferred language', type: 'select', options: ['English', 'Spanish', 'French', 'Portuguese'] },
    ],
  }),
  surface({
    key: 'unified-signup',
    phase: 'I',
    phaseItem: '1.2.',
    checklistLabel: 'Unified Signup Portal',
    title: 'Create Your Church Account',
    slug: 'signup',
    kind: 'gateway',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/auth/member-register',
    moduleKey: 'members',
    summary: 'Register visitors and members into the active tenant workspace with secure account context.',
    primaryAction: 'Create Account',
    fields: [...basicIdentityFields, { name: 'password', label: 'Password', type: 'text', required: true }, consentField],
  }),
  surface({
    key: 'unified-signin',
    phase: 'I',
    phaseItem: '1.3.',
    checklistLabel: 'Unified Sign-In Portal',
    title: 'Sign In',
    slug: 'sign-in',
    kind: 'gateway',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/auth/login',
    moduleKey: 'members',
    summary: 'Authenticate members through password, social, or device-key pathways without browser-native prompts.',
    primaryAction: 'Sign In',
    fields: [
      { name: 'email', label: 'Email address', type: 'email', required: true },
      { name: 'password', label: 'Password', type: 'text', required: true },
    ],
  }),
  surface({
    key: 'password-recovery',
    phase: 'I',
    phaseItem: '1.4.',
    checklistLabel: 'Self-Service Password Recovery Portal',
    title: 'Recover Password',
    slug: 'password-recovery',
    kind: 'gateway',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/auth/password-recovery',
    moduleKey: 'members',
    summary: 'Request a localized password recovery link while keeping server and token detail hidden.',
    primaryAction: 'Send Recovery Link',
    fields: [{ name: 'email', label: 'Account email', type: 'email', required: true }],
  }),
  surface({
    key: 'member-only-intercept',
    phase: 'I',
    phaseItem: '2.1.',
    checklistLabel: 'Verified Member-Only Access Intercept Screen',
    title: 'Member Access Required',
    slug: 'member-access-required',
    kind: 'access',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/frontend-surfaces/member-access-required/action',
    moduleKey: 'members',
    summary: 'Blocks protected resources and guides visitors into verified member authentication.',
    primaryAction: 'Sign In Securely',
    secondaryAction: 'Request Access',
  }),
  surface({
    key: 'password-content-gate',
    phase: 'I',
    phaseItem: '2.2.',
    checklistLabel: 'Password-Protected Content Gate Screen',
    title: 'Protected Content',
    slug: 'password-gate',
    kind: 'access',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/frontend-surfaces/password-gate/submit',
    moduleKey: 'content-management',
    summary: 'Inline passphrase gate for private landing pages and campaign resources.',
    primaryAction: 'Unlock Content',
    fields: [{ name: 'passphrase', label: 'Access passphrase', type: 'text', required: true }],
  }),
  surface({
    key: 'suspended-workspace',
    phase: 'I',
    phaseItem: '2.3.',
    checklistLabel: 'Suspended Workspace Workspace Screen',
    title: 'Workspace Temporarily Paused',
    slug: 'workspace-suspended',
    kind: 'access',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/billing-subscription-management',
    moduleKey: 'billing',
    summary: 'Branded suspension intercept for archived, delinquent, or paused tenant workspaces.',
    primaryAction: 'Contact Workspace Owner',
  }),
  surface({
    key: 'permission-setup-modal',
    phase: 'I',
    phaseItem: '3.1.',
    checklistLabel: 'Microphone & Camera Permission Setup Modal',
    title: 'Camera and Microphone Setup',
    slug: 'permission-setup',
    kind: 'permission',
    placement: 'global',
    renderMode: 'blueprint',
    endpoint: '/api/frontend-surfaces/permission-setup/action',
    moduleKey: 'live-meetings',
    summary: 'Explains hardware access before any browser permission API is invoked.',
    primaryAction: 'Continue Setup',
  }),
  surface({
    key: 'hardware-denied-modal',
    phase: 'I',
    phaseItem: '3.2.',
    checklistLabel: 'Hardware Access Denied Intercept Modal',
    title: 'Hardware Access Blocked',
    slug: 'hardware-denied',
    kind: 'permission',
    placement: 'global',
    renderMode: 'blueprint',
    endpoint: '/api/frontend-surfaces/hardware-denied/action',
    moduleKey: 'live-meetings',
    summary: 'Guides members through OS and browser settings when hardware access is denied.',
    primaryAction: 'Show Fix Steps',
  }),
  surface({
    key: 'rbac-session-mismatch',
    phase: 'I',
    phaseItem: '3.3.',
    checklistLabel: 'RBAC Session Mismatch Alert Modal',
    title: 'Session Permission Mismatch',
    slug: 'rbac-session-mismatch',
    kind: 'permission',
    placement: 'global',
    renderMode: 'blueprint',
    endpoint: '/api/frontend-surfaces/rbac-session-mismatch/action',
    moduleKey: 'user-role-management',
    summary: 'Blocks privileged links when the active member session lacks the required scope.',
    primaryAction: 'Switch Session',
  }),

  surface({
    key: 'homepage',
    phase: 'II',
    phaseItem: '1.1.',
    checklistLabel: 'Homepage',
    title: 'Homepage',
    slug: '',
    aliases: ['home'],
    kind: 'standalone',
    placement: 'header',
    renderMode: 'static',
    endpoint: '/api/cms/render?slug=',
    moduleKey: 'content-management',
    summary: 'Existing Ecclesia home template preserved and enriched by global overlays and tenant headers.',
    primaryAction: 'Plan Your Visit',
    existingTemplate: 'index.html',
  }),
  surface({
    key: 'about-page',
    phase: 'II',
    phaseItem: '1.2.',
    checklistLabel: 'About Page',
    title: 'About',
    slug: 'about',
    kind: 'standalone',
    placement: 'header',
    renderMode: 'static',
    endpoint: '/api/cms/render?slug=about',
    moduleKey: 'content-management',
    summary: 'Existing About structure preserved for mission, beliefs, history, and leadership sections.',
    primaryAction: 'Meet the Church',
    existingTemplate: 'about.html',
  }),
  surface({
    key: 'contact-page',
    phase: 'II',
    phaseItem: '1.3.',
    checklistLabel: 'Contact Page',
    title: 'Contact',
    slug: 'contact',
    kind: 'standalone',
    placement: 'header',
    renderMode: 'static',
    endpoint: '/api/cms/render?slug=contact',
    moduleKey: 'content-management',
    summary: 'Existing Contact page preserved with custom validation and network alert interception.',
    primaryAction: 'Get in Touch',
    existingTemplate: 'contact.html',
  }),
  surface({
    key: 'service-times',
    phase: 'II',
    phaseItem: '1.4.',
    checklistLabel: 'Service Times & Gatherings Page',
    title: 'Service Times and Gatherings',
    slug: 'service-times',
    kind: 'standalone',
    placement: 'header',
    renderMode: 'blueprint',
    endpoint: '/api/services',
    moduleKey: 'church-services',
    summary: 'Weekly services, campus variants, directions, childcare notes, and next gathering cues.',
    primaryAction: 'Plan This Sunday',
  }),
  surface({
    key: 'campus-profiles',
    phase: 'II',
    phaseItem: '1.5.',
    checklistLabel: 'Branch/Campus Profiles Page',
    title: 'Campus Profiles',
    slug: 'campuses',
    kind: 'standalone',
    placement: 'header',
    renderMode: 'blueprint',
    endpoint: '/api/branches',
    moduleKey: 'multi-branch',
    summary: 'Campus pastors, local livestreams, office contacts, maps, and localized events.',
    primaryAction: 'Choose Campus',
  }),
  surface({
    key: 'ministries-hub',
    phase: 'II',
    phaseItem: '1.6.',
    checklistLabel: 'Ministries Hub Page',
    title: 'Ministries',
    slug: 'ministries',
    kind: 'standalone',
    placement: 'header',
    renderMode: 'static',
    endpoint: '/api/cms/render?slug=ministries',
    moduleKey: 'content-management',
    summary: 'Existing Ministries hub preserved and connected to form funnels.',
    primaryAction: 'Join a Ministry',
    existingTemplate: 'ministries.html',
  }),
  surface({
    key: 'events-calendar',
    phase: 'II',
    phaseItem: '1.7.',
    checklistLabel: 'Events Calendar Page',
    title: 'Events Calendar',
    slug: 'events',
    kind: 'standalone',
    placement: 'header',
    renderMode: 'static',
    endpoint: '/api/cms/render?slug=events',
    moduleKey: 'events',
    summary: 'Existing event calendar preserved with tenant-scoped filters and custom RSVP overlays.',
    primaryAction: 'View Events',
    existingTemplate: 'events.html',
  }),
  surface({
    key: 'sermon-media-archive',
    phase: 'II',
    phaseItem: '2.1.',
    checklistLabel: 'Sermon & Media Library Archive',
    title: 'Sermon and Media Library',
    slug: 'media',
    aliases: ['sermons'],
    kind: 'archive',
    placement: 'rail',
    renderMode: 'static',
    endpoint: '/api/media',
    moduleKey: 'media',
    summary: 'Existing media archive preserved with archive placement in the side rail.',
    primaryAction: 'Browse Sermons',
    existingTemplate: 'media-archive.html',
  }),
  surface({
    key: 'blog-devotional-index',
    phase: 'II',
    phaseItem: '2.2.',
    checklistLabel: 'Dynamic Blog & Devotional Index',
    title: 'Articles and Devotionals',
    slug: 'blog',
    kind: 'archive',
    placement: 'rail',
    renderMode: 'static',
    endpoint: '/api/blog',
    moduleKey: 'blog',
    summary: 'Existing blog archive preserved as an archive rail page.',
    primaryAction: 'Read Articles',
    existingTemplate: 'blog-archive.html',
  }),
  surface({
    key: 'resource-hub',
    phase: 'II',
    phaseItem: '2.3.',
    checklistLabel: 'Digital Library & Resource Hub',
    title: 'Digital Library',
    slug: 'library',
    kind: 'archive',
    placement: 'rail',
    renderMode: 'static',
    endpoint: '/api/library',
    moduleKey: 'library',
    summary: 'Existing resource archive preserved with download and member-only indicators.',
    primaryAction: 'Browse Resources',
    existingTemplate: 'library-archive.html',
  }),
  surface({
    key: 'podcast-directory',
    phase: 'II',
    phaseItem: '2.4.',
    checklistLabel: 'Podcasts Directory Page',
    title: 'Podcasts',
    slug: 'podcast',
    kind: 'archive',
    placement: 'rail',
    renderMode: 'static',
    endpoint: '/api/podcast',
    moduleKey: 'podcast',
    summary: 'Existing podcast directory preserved with RSS and audio actions.',
    primaryAction: 'Listen Now',
    existingTemplate: 'podcast-archive.html',
  }),
  surface({
    key: 'storefront',
    phase: 'II',
    phaseItem: '2.5.',
    checklistLabel: 'E-Commerce Store Page',
    title: 'Church Store',
    slug: 'store',
    kind: 'archive',
    placement: 'rail',
    renderMode: 'blueprint',
    endpoint: '/api/store/products',
    moduleKey: 'store',
    summary: 'Merchandise, books, event gear, variants, pickup preferences, and checkout triggers.',
    primaryAction: 'Open Cart',
  }),
  surface({
    key: 'cell-directory',
    phase: 'II',
    phaseItem: '2.6.',
    checklistLabel: 'Cell / Fellowship Directory Page',
    title: 'Cell and Fellowship Directory',
    slug: 'cells',
    kind: 'archive',
    placement: 'rail',
    renderMode: 'blueprint',
    endpoint: '/api/cells',
    moduleKey: 'cell-fellowship',
    summary: 'Location-aware group finder with affinity filters and direct group joining links.',
    primaryAction: 'Find a Cell',
  }),

  surface({
    key: 'service-record',
    phase: 'III',
    phaseItem: '',
    checklistLabel: 'Individual Service Record Page',
    title: 'Service Record',
    slug: 'services/sample-service',
    kind: 'detail',
    placement: 'none',
    renderMode: 'static',
    endpoint: '/api/church-services',
    moduleKey: 'church-services',
    summary: 'Existing individual service template with videos, audio, outlines, and metadata.',
    primaryAction: 'Review Service',
    existingTemplate: 'service-single.html',
  }),
  surface({
    key: 'media-detail',
    phase: 'III',
    phaseItem: '',
    checklistLabel: 'Single Media / Sermon Detail View',
    title: 'Sermon Detail',
    slug: 'media/sample-message',
    aliases: ['sermons/sample-message'],
    kind: 'detail',
    placement: 'none',
    renderMode: 'static',
    endpoint: '/api/media',
    moduleKey: 'media',
    summary: 'Existing media detail template with media player and related speaker links.',
    primaryAction: 'Play Sermon',
    existingTemplate: 'media-single.html',
  }),
  surface({
    key: 'blog-detail',
    phase: 'III',
    phaseItem: '',
    checklistLabel: 'Single Blog Article / Devotional Post',
    title: 'Article Detail',
    slug: 'blog/sample-post',
    kind: 'detail',
    placement: 'none',
    renderMode: 'static',
    endpoint: '/api/blog',
    moduleKey: 'blog',
    summary: 'Existing article template with readable devotional typography and related posts.',
    primaryAction: 'Read Article',
    existingTemplate: 'blog-single.html',
  }),
  surface({
    key: 'resource-detail',
    phase: 'III',
    phaseItem: '',
    checklistLabel: 'Single Resource View & Download Screen',
    title: 'Resource Download',
    slug: 'library/sample-resource',
    kind: 'detail',
    placement: 'none',
    renderMode: 'static',
    endpoint: '/api/library',
    moduleKey: 'library',
    summary: 'Existing resource detail template with file size, license, and download actions.',
    primaryAction: 'Download Resource',
    existingTemplate: 'resource-single.html',
  }),
  surface({
    key: 'podcast-episode',
    phase: 'III',
    phaseItem: '',
    checklistLabel: 'Single Podcast Episode Player Page',
    title: 'Podcast Episode',
    slug: 'podcast/sample-episode',
    kind: 'detail',
    placement: 'none',
    renderMode: 'static',
    endpoint: '/api/podcast',
    moduleKey: 'podcast',
    summary: 'Existing episode player template with cover art, notes, and subscription tools.',
    primaryAction: 'Play Episode',
    existingTemplate: 'podcast-episode.html',
  }),
  surface({
    key: 'product-detail',
    phase: 'III',
    phaseItem: '',
    checklistLabel: 'Single E-Commerce Product Details Page',
    title: 'Product Details',
    slug: 'store/sample-product',
    kind: 'detail',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/store/products/sample-product',
    moduleKey: 'store',
    summary: 'Product media, size and color variants, stock counts, and pickup or delivery preferences.',
    primaryAction: 'Add to Cart',
  }),
  surface({
    key: 'event-detail',
    phase: 'III',
    phaseItem: '',
    checklistLabel: 'Single Event Detail & Booking Page',
    title: 'Event Detail',
    slug: 'events/sample-event',
    kind: 'detail',
    placement: 'none',
    renderMode: 'static',
    endpoint: '/api/events',
    moduleKey: 'events',
    summary: 'Existing event detail template with schedule, speakers, maps, and booking actions.',
    primaryAction: 'Book Event',
    existingTemplate: 'event-single.html',
  }),

  ...[
    ['new-visitor', 'New Visitor / Guest Connection Card Form', 'CRM visitor intake and first-time visit source details.', 'crm'],
    ['prayer-request', 'Prayer Request Intake Form', 'Private or public prayer needs routed to intercessory teams.', 'prayer'],
    ['testimony-submission', 'Testimony Submission & Media Upload Form', 'Text, audio, or video praise report upload with release consent.', 'prayer'],
    ['baptism-registration', 'Water Baptism Registration Form', 'Baptism preparation, class selection, and size details.', 'members'],
    ['volunteer-application', 'Volunteer & Worker Application Form', 'Skills, departments, availability, and background screening consent.', 'volunteer'],
    ['care-request', 'Counselling & Care Request Intake Form', 'Care category, personal history summary, and appointment preferences.', 'bookings'],
    ['mentorship-application', 'Mentorship Application Form', 'Structured discipleship mentorship enrollment.', 'lms'],
    ['pastoral-appointment', 'Pastoral Appointment Intake Form', 'Pre-appointment checklist for pastoral leadership meetings.', 'bookings'],
    ['conference-registration', 'Conference / Special Event Registration Form', 'Conference attendee data, meals, shirts, and ticket variations.', 'events'],
    ['seminar-registration', 'Seminar / Workshop Registration Form', 'Training track registration for smaller learning gatherings.', 'events'],
    ['outreach-response', 'Crusade / Outreach Response Form', 'Physical or online outreach leads and decision follow-up.', 'outreach'],
    ['concert-tickets', 'Concert / Ticket Purchase Form', 'Ticket distribution and secure checkout intake.', 'events'],
    ['retreat-signup', 'Retreat / Special Program Sign-up Form', 'Retreat waivers, special program consent, and file upload checks.', 'events'],
    ['salvation-response', 'Salvation Response & New Believer Confirmation Form', 'Sensitive altar-call and new believer follow-up capture.', 'salvation'],
    ['cell-joining', 'Cell Group / Home Fellowship Joining Form', 'Location-aware mapping into neighborhood fellowship groups.', 'cell-fellowship'],
    ['course-enrollment', 'LMS Discipleship Course Enrollment Form', 'Student self-registration for the discipleship academy.', 'lms'],
    ['lesson-quiz', 'LMS Lesson Quiz / Assessment Form', 'Lesson assessment responses mapped to course progress.', 'lms'],
    ['children-registration', 'Children & Family Ministry Registration Form', 'Household, guardian, emergency, and pickup authorization setup.', 'children'],
    ['child-medical-alert', 'Child Allergy & Special Medical Alert Intake Form', 'High-contrast allergy and medical flags for check-in safety.', 'children'],
    ['vbs-kids-camp', 'Vacation Bible School (VBS) / Kids Camp Sign-up Form', 'Kids camp registration with parent waivers and medical history.', 'children'],
    ['partnership-pledge', 'Recurring Ministry Partnership Pledge Form', 'Ongoing monthly ministry partnership pledge capture.', 'partnerships'],
    ['campaign-contribution', 'Goal-Based Campaign Contribution Form', 'Campaign gift narrative tied to dedicated fundraising goals.', 'campaigns'],
    ['thanksgiving-offering', 'Thanksgiving Offering Narrative Form', 'Gratitude narrative attached to an offering transaction.', 'giving'],
    ['admin-feedback', 'General Administrative Inquiry & Feedback Form', 'Administrative inquiries and feedback routed from public channels.', 'forms'],
  ].map(([slug, title, summary, moduleKey], index) => surface({
    key: `form-${slug}`,
    phase: 'IV' as SurfacePhaseKey,
    phaseItem: '',
    checklistLabel: title,
    title,
    slug,
    kind: 'form' as SurfaceKind,
    placement: slug === 'new-visitor' ? 'header' : 'none',
    renderMode: 'blueprint' as SurfaceRenderMode,
    endpoint: `/api/frontend-surfaces/${slug}/submit`,
    moduleKey,
    summary,
    primaryAction: index === 16 ? 'Submit Quiz' : index === 21 || index === 22 ? 'Continue to Giving' : 'Submit Securely',
    fields: [
      ...registrationFields,
      { name: 'requestType', label: 'Request type', type: 'select', required: true, options: ['New request', 'Follow-up', 'Update existing record'] },
      { name: 'message', label: 'Details', type: 'textarea', required: true },
      consentField,
    ],
  })),

  surface({
    key: 'member-dashboard',
    phase: 'V',
    phaseItem: '1.1.',
    checklistLabel: 'Personal Member Dashboard',
    title: 'Member Dashboard',
    slug: 'account',
    kind: 'portal',
    placement: 'rail',
    renderMode: 'static',
    endpoint: '/api/members/me',
    moduleKey: 'members',
    summary: 'Existing account template preserved for giving, shifts, profile, and study bookmarks.',
    primaryAction: 'Open Dashboard',
    existingTemplate: 'account.html',
  }),
  surface({
    key: 'academy-dashboard',
    phase: 'V',
    phaseItem: '1.2.',
    checklistLabel: 'LMS Student Academy Dashboard',
    title: 'Academy Dashboard',
    slug: 'academy-dashboard',
    kind: 'portal',
    placement: 'rail',
    renderMode: 'blueprint',
    endpoint: '/api/lms',
    moduleKey: 'lms',
    summary: 'Course progress, next lessons, assignments, grades, and certificate status.',
    primaryAction: 'Continue Course',
  }),
  surface({
    key: 'student-lesson-quiz',
    phase: 'V',
    phaseItem: '1.3.',
    checklistLabel: 'Student Lesson & Quiz Interface',
    title: 'Lesson and Quiz',
    slug: 'courses/lesson',
    kind: 'portal',
    placement: 'none',
    renderMode: 'static',
    endpoint: '/api/lms',
    moduleKey: 'lms',
    summary: 'Existing lesson template preserved with video, quiz, and outline downloads.',
    primaryAction: 'Submit Quiz',
    existingTemplate: 'lesson-single.html',
  }),
  surface({
    key: 'lineage-tree',
    phase: 'V',
    phaseItem: '2.1.',
    checklistLabel: 'Historical Group Lineage Tree Page',
    title: 'Cell Lineage Tree',
    slug: 'cell-lineage',
    kind: 'portal',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/cells',
    moduleKey: 'cell-fellowship',
    summary: 'Front-facing visualization of cell multiplication and leadership lineage.',
    primaryAction: 'Inspect Lineage',
  }),
  surface({
    key: 'promotion-scorecard',
    phase: 'V',
    phaseItem: '2.2.',
    checklistLabel: 'Interactive Cell Promotion Scorecard Page',
    title: 'Cell Promotion Scorecard',
    slug: 'cell-scorecard',
    kind: 'portal',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/cells',
    moduleKey: 'cell-fellowship',
    summary: 'Attendance, giving consistency, outreach, and split-readiness scorecard.',
    primaryAction: 'Review Score',
  }),

  surface({
    key: 'livestream-broadcast',
    phase: 'VI',
    phaseItem: '',
    checklistLabel: 'Livestream Broadcast Screen',
    title: 'Livestream Broadcast',
    slug: 'livestream',
    kind: 'immersive',
    placement: 'rail',
    renderMode: 'static',
    endpoint: '/api/livestream',
    moduleKey: 'livestream',
    summary: 'Existing livestream room preserved with chat, Bible notes, and action tabs.',
    primaryAction: 'Watch Live',
    existingTemplate: 'livestream-page.html',
  }),
  surface({
    key: 'corporate-prayer-room',
    phase: 'VI',
    phaseItem: '',
    checklistLabel: 'Immersive Corporate Prayer Room Page',
    title: 'Corporate Prayer Room',
    slug: 'prayer/room',
    kind: 'immersive',
    placement: 'none',
    renderMode: 'static',
    endpoint: '/api/prayer',
    moduleKey: 'prayer',
    summary: 'Existing prayer room preserved with participant counters and prayer confirmations.',
    primaryAction: 'Join Prayer',
    existingTemplate: 'prayer-room.html',
  }),
  surface({
    key: 'prayer-leader',
    phase: 'VI',
    phaseItem: '',
    checklistLabel: 'Delegated Prayer Leader Interface',
    title: 'Prayer Leader Console',
    slug: 'prayer-leader',
    kind: 'immersive',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/prayer/sessions/sample/settings',
    moduleKey: 'prayer',
    summary: 'Leader controls for audio, video, background music, and prayer point pacing.',
    primaryAction: 'Start Leading',
  }),
  surface({
    key: 'meeting-room',
    phase: 'VI',
    phaseItem: '',
    checklistLabel: 'Live Video Meeting Room',
    title: 'Live Meeting Room',
    slug: 'meeting-room',
    kind: 'immersive',
    placement: 'none',
    renderMode: 'blueprint',
    endpoint: '/api/meetings',
    moduleKey: 'live-meetings',
    summary: 'WebRTC classroom and small group workspace with chat, screenshare, and lyric overlay areas.',
    primaryAction: 'Join Meeting',
  }),

  ...[
    ['global-live-chat', 'Floating Web Live Chat Bubble', 'chat'],
    ['global-cart-drawer', 'Sliding Shopping Cart Drawer', 'store'],
    ['global-mini-player', 'Floating Sermon Mini-Player (Picture-in-Picture)', 'media'],
    ['global-notice-board', 'Sliding Notice Board Messaging Thread Component', 'cell-fellowship'],
  ].map(([slug, title, moduleKey]) => surface({
    key: slug,
    phase: 'VII' as SurfacePhaseKey,
    phaseItem: '',
    checklistLabel: title,
    title,
    slug,
    kind: 'global' as SurfaceKind,
    placement: 'global',
    renderMode: 'embedded' as SurfaceRenderMode,
    endpoint: `/api/frontend-surfaces/${slug}/action`,
    moduleKey,
    summary: 'Injected globally across the Ecclesia shell with custom drawer or floating component behavior.',
    primaryAction: 'Open Component',
  })),

  ...[
    ['module-disabled', '1.1.', '"Module Disabled" Placeholder Layout', 'Disabled module placeholder for manually entered inactive module routes.'],
    ['empty-state', '1.2.', 'Interactive Page "Empty State" Templates', 'Dashboard and archive empty states with clear next actions.'],
    ['search-no-results', '1.3.', 'Global Search "No Results" Layout', 'Helpful no-results state for filters and search boxes.'],
    ['order-status', '2.1.', 'E-Commerce Physical Order Status & Pickup Voucher View', 'Pickup voucher, order status, QR code, and fulfillment details.'],
    ['ticket-retrieval', '2.2.', 'Digital Ticket Retrieval Screen', 'Ticket details, QR code, calendar actions, and campus directions.'],
    ['domain-dns-setup', '2.3.', 'Custom Domain DNS Setup Instructions View', 'CNAME, A record, SSL, and verification instructions.'],
  ].map(([slug, phaseItem, title, summary]) => surface({
    key: `state-${slug}`,
    phase: 'VIII' as SurfacePhaseKey,
    phaseItem,
    checklistLabel: title,
    title,
    slug,
    kind: 'state' as SurfaceKind,
    placement: 'none',
    renderMode: 'blueprint' as SurfaceRenderMode,
    endpoint: slug === 'domain-dns-setup' ? '/api/tenant/domain' : `/api/frontend-surfaces/${slug}/action`,
    moduleKey: slug === 'domain-dns-setup' ? 'domain-tenant-management' : 'content-management',
    summary,
    primaryAction: 'Continue',
  })),

  ...[
    ['form-error-modal', '1.1.', 'Custom Form Input Error Alert Modal', 'Points incomplete fields to custom corrective blocks.'],
    ['file-warning-modal', '1.2.', 'File Format & Oversize Warning Modal', 'Blocks invalid upload format and file size issues.'],
    ['invalid-coupon-modal', '1.3.', 'Invalid Coupon Code Intercept Modal', 'Keeps checkout data intact while explaining coupon errors.'],
    ['logout-confirm-modal', '2.1.', 'Logout Confirmation Safety Modal', 'Confirms member sign-out without native confirm boxes.'],
    ['dirty-form-modal', '2.2.', 'Unsaved Progress / Dirty Form Intercept Modal', 'Stops accidental navigation away from a draft.'],
    ['cancel-booking-modal', '2.3.', 'Order / Booking Cancellation Confirm Modal', 'Explains cancellation, refund, and reschedule consequences.'],
    ['video-settings-modal', '3.1.', 'Video Playback Settings Over-layer', 'Controls subtitle, language, and playback rate selections.'],
    ['external-media-fallback-modal', '3.2.', 'External Media Link Fallback Modal', 'Provides alternate stream links when embeds fail.'],
    ['network-alert-modal', '3.3.', 'Network Interruption Alert Modal', 'Shows reconnection and draft preservation status.'],
    ['recording-consent-modal', '4.1.', 'Meeting Recording Consent Modal', 'Blocks meeting entry until recording consent is handled.'],
    ['quiz-score-modal', '4.2.', 'Quiz Score & Module Progression Modal', 'Displays score, pass status, and next module unlock.'],
    ['course-nudge-modal', '4.3.', 'Course Incomplete Nudge Modal', 'Blocks skipped lessons until prerequisites are complete.'],
    ['invite-copied-toast', '4.4.', 'Personal Invite Link Copied Toast', 'Confirms copied invite tracking links with a custom toast.'],
    ['verse-card-modal', '4.5.', 'Custom Graphics / Verse Card Canvas Modal', 'Previews social-ready scripture graphics.'],
    ['tenant-session-sync-toast', '4.6.', 'Multi-Tenant Session Sync Toast Alert', 'Warns when session and active tenant domain drift apart.'],
  ].map(([slug, phaseItem, title, summary]) => surface({
    key: `modal-${slug}`,
    phase: 'IX' as SurfacePhaseKey,
    phaseItem,
    checklistLabel: title,
    title,
    slug,
    kind: 'modal' as SurfaceKind,
    placement: 'global',
    renderMode: 'embedded' as SurfaceRenderMode,
    endpoint: `/api/frontend-surfaces/${slug}/action`,
    moduleKey: 'theme-engine',
    summary,
    primaryAction: 'Preview Modal',
  })),
];

const surfaceBySlug = new Map<string, BlueprintSurface>();

for (const item of SURFACE_CATALOG) {
  surfaceBySlug.set(item.slug, item);
  item.aliases?.forEach((alias) => surfaceBySlug.set(alias, item));
}

export function getBlueprintSurfaceForSlug(slug: string): BlueprintSurface | null {
  return surfaceBySlug.get(slug.replace(/^\/+|\/+$/g, '')) || null;
}

export function shouldRenderBlueprintSurface(slug: string): boolean {
  const surfaceDef = getBlueprintSurfaceForSlug(slug);
  return Boolean(surfaceDef && surfaceDef.renderMode === 'blueprint');
}

export function getPhaseSurfaces(phase: SurfacePhaseKey): BlueprintSurface[] {
  return SURFACE_CATALOG.filter((item) => item.phase === phase);
}

export function getCompletedSurfaceCount(): number {
  return SURFACE_CATALOG.length;
}

export const HEADER_BLUEPRINT_NAV = SURFACE_CATALOG
  .filter((item) => item.placement === 'header')
  .map((item) => ({ label: item.title === 'Homepage' ? 'Home' : item.title.replace(' and ', ' & '), url: item.slug ? `/${item.slug}` : '/' }));

export const RAIL_BLUEPRINT_NAV = [
  { label: 'Media', path: '/media', icon: 'Tv' },
  { label: 'Services', path: '/services', icon: 'Calendar' },
  { label: 'Articles', path: '/blog', icon: 'Newspaper' },
  { label: 'Library', path: '/library', icon: 'BookOpen' },
  { label: 'Podcast', path: '/podcast', icon: 'Mic' },
  { label: 'Store', path: '/store', icon: 'ShoppingBag' },
  { label: 'Cells', path: '/cells', icon: 'UsersRound' },
  { label: 'LMS', path: '/courses', icon: 'GraduationCap' },
  { label: 'Worship', path: '/worship', icon: 'Music' },
  { label: 'Account', path: '/account', icon: 'UserCircle' },
] as const;

export const RAIL_BLUEPRINT_PATHS: Set<string> = new Set(RAIL_BLUEPRINT_NAV.map((item) => item.path));
