name = "churchos-api"
main = "src/server.ts"
compatibility_date = "2026-05-28"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"

[experimental]
# This worker will need a build step and custom adapter support.
